### ISSUE TITLE
Optimize WorldWind when the re-render occurs for multiPoint mil std shapes

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#143]
Re-rendering is occurring too often and is affecting performance when panning the map.
Direct pans with no tilt or rotation should probably not trigger a re-render
## Things to take into account for optimization
* altitude changes
* tilt/heading changes
* panning while tilted only if the sky is visible

**Comment by alberto-acevedo** [comment]
Test case:

use branch feature/ #143

This is not easy to test because it is hard to tell if the graphics are re rendering in WW.
Use the API tester.  Use the multipoint performance tester. Plot  200 multipoints. Zooming in and out, do panning of the map, map tilting, etc. The test is a success if the graphics re renderer and also if  the re rendering is faster.  The test fails if there is the presence of clipped graphics.

**Comment by jamesbeecroft** [comment]
Reintegrate. Panning, zooming, and tilting is a little choppy, but graphics are fine.
