### ISSUE TITLE
Leaflet is not raising FeatureUserInteractionEvents for MOUSE_UP and MOUSE_DOWN

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#17]
Leaflet will raise a FeatureUserInteractionEvent for CLICKED, but does not raise them for MOUSE_UP and MOUSE_DOWN.  Fix so that when you mouse down over a feature the MOUSE_DOWN event type is raised on the FeatureUserInteractionEvent and on the mouse up send a FeatureUserInteraction event with the MOUSE_UP event type.

As per #13 , you will need this for Leaflet point editors to continue working.

**Comment by nclark25** [comment]
The current version of the Leaflet SDK (0.7.3) residing in EMP does not have native support for mouseDown and mouseUp events on Feature Groups. It does provide support for click events on Feature Groups which is already implemented by adding a listener on the Feature Group when it is created. @Ish-rivera and I have tried adding mouseDown and mouseUp events to the Feature Group event list in the Leaflet SDK and subsequently added listeners for these "new" events to the initialization/creation section for features. These new events fire without issue, but for some reason after a drag operation on the map the Feature Group click events will stop working. In this state only the mouseDown and mouseUp events on the Feature Group will fire when clicking on the Feature Group. To reset this, a click on the map section must occur which will allow all events to fire properly again. Because of this issue I had decided to place the new Leaflet SDK (1.0.3) and do a trial to see if this issue was fixed. Although I could not replicate the issue with SDK (1.0.3), testing other functionality with the validation tester has revealed that the leaflet-eng.leaflet.extensions.js file will need to be updated. This file contains utility functions (shouldn't need to change) along with Leaflet class extensions that essentially are used to override some of the native Leaflet class functions for EMP specific use. These overridden functions keep most of the same functionality as the native Leaflet class functions with a few tweaks. These tweaks in some cases are different calculations which depending on the updates that occurred in the new SDK (1.0.3) may not be needed anymore or they may need to be kept. I have already gone through the leaflet-eng.leaflet.extensions.js file and put a comment on each function to identifying it as overridden or a utility function.

This issue will most likely be fixed with an upgrade of the Leaflet SDK but more time will be needed because of the leaflet-eng.leaflet.extensions.js checks and potential modifications. As a result, I tried a workaround in which extraction of Feature Groups occurs during a Map mouseDown and mouseUp event. I was hoping that the layer (Leaflet layers, not EMP layers) listing provided during a mouseDown and mouseUp operation was specific to the location that was clicked on the map. Unfortunately, this was not the case as Leaflet provides a comprehensive list of layers when clicking anywhere on the map. This resulted in Feature mouseDown and mouseUp events firing no matter where you clicked on the map.

**Comment by nclark25** [comment]
Finished going through leaflet-eng.leaflet.extensions.js file. Now testing plotting of graphics with Leaflet 1.0.3. Keep getting an error in relation to wrap() not being a function because emp3-web -> leafLet.utils.wrapCoordinates() is expecting a flat array for the coordinates parameter. Flat array worked in Leaflet version 0.7.3. However, an update was performed -> Leaflet/Leaflet#3279 in which L.Polygons can never be flat. Therefore, the wrap() invocation is attempted on the outer array instead of each L.LatLng object residing inside.

**Comment by nclark25** [comment]
Fixes for both simple graphics and mil-std wrap() function have been implemented and all tested graphics seem to be plotting correctly.

**Comment by jamesbeecroft** [comment]
Findings from Testing Leaflet 3/1/17 - 3/2/17
1. Mil-Std graphics created via test script or through normal creation procedures are not rendering in Leaflet, with the exception of Point of Departure. 
2. Mil-Std units are not rendering in Leaflet with the echelon displayed when assigned. 
3. URL Proxy is not enabled in Leaflet (WMS)
4. Unsure if WMTS is incorporated into Leaflet Functionality (Nick Clark follow up)
5. Map Event Testing Results:
Feature Event (on selection) does not fire, selection does occur
LookAt does not fire, setting and getting look at both occur
MapFreeHandDraw does not fire

**Comment by nclark25** [comment]
The style for paths is not updating in the new version of Leaflet. Leaflet now has an SVG class that is used for Paths.

**Comment by nclark25** [comment]
> Findings from Testing Leaflet 3/1/17 - 3/2/17

>     Mil-Std graphics created via test script or through normal creation procedures are not rendering in Leaflet, with the exception of Point of Departure.
^ There was a duplicate branch created and Jimmy was pointing to it by mistake. The branch he was pointing to did not have the fixes for this.

>     Mil-Std units are not rendering in Leaflet with the echelon displayed when assigned.
^ The midDistanceThreshold and the farDistanceThreshold were set to close to be able to see the echelon. These are displaying but the DTG is not. This most likely has nothing to do with the new version of leaflet though so we should write up an issue for it.

>     URL Proxy is not enabled in Leaflet (WMS)
^ An issue should be written up for this.

>     Unsure if WMTS is incorporated into Leaflet Functionality (Nick Clark follow up)
^ According to the Leaflet documentation there is support for TMS and WMS. If WMTS is a requirement its data structure would have to be implemented and based off of TMS most likely. I seem to remember @sjpinizzotto having to do something with this in the past?

>     Map Event Testing Results:
>     Feature Event (on selection) does not fire, selection does occur
>     LookAt does not fire, setting and getting look at both occur
>     MapFreeHandDraw does not fire
^ Feature Event is not implemented in the API. I didn't see any use of a LookAt enumeration in the message handler and MapFreeHandDraw is not implemented in Leaflet.

>     Geojson fails to add to the map.
>     leaflet_geojson_error
>     Link to Geojson used.
>     https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json
^ This has been fixed

>     KML Layer not enabled in Leaflet.
^ This is a feature that will be implemented in Leaflet at some point.
