### ISSUE TITLE
A mouse up off the map while user is in middle of edit causes editing to break.

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#257]
Place a line or polygon in edit or draw mode.   Edit an existing point by dragging on it, do not let go.  Move the mouse over an area of the browser outside of the map.   Let go of the drag.   At this point the map thinks the mouse is still down and if you move the cursor back on the map it will follow the mouse cursor as if you still had the mouse down.   If a compelteDraw occurs it will leave the animation line on the map.  The map is stuck in smart motion after that.  Only another draw and drag on a point can fix this.

**Comment by alberto-acevedo** [comment]
-Fixed by removing the animation feature  inside  the editingManager complete function.
-Fixed by calling   this.editMouseUp() to unlock map    inside  the editingManager complete function.
- Fixed issue in the editingManager complete function that was failing to update the editing feature. The transaction item  (feature)'s overlay id was getting modified by previous transactions. Fixed by making a copy of the editor's  feature. The core is expecting an overlayId = "ALL PARENTS" to allow the transaction to update the feature in the engine when in edit mode..

**Comment by alberto-acevedo** [comment]
test case:

use branch 326.
Plot a polygon.
Edit the polygon.
click a control point and drag the mouse outside the map and then release the  mouse. Then complete the edit operation. The test is a success if the animation line is not present, and the map is not locked.

Repeat test for the case of lines .

Repeat the test for the case of block tasks. The editor for this graphic is not using animation. The test is a success if the map is not  locked.

**Comment by mubinakhan** [comment]
Reintegrate

**Comment by alberto-acevedo** [comment]
Merged into the dev branch. closing this issue.
