### ISSUE TITLE
WorldWind needs to be updated to be able to handle useProxy when necessary

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#97]
WorldWind placemarks are currently set to be used in their raw value. The useProxy property is not being used.

**Comment by alberto-acevedo** [comment]
test case:

use branch 97

Plot a primitive point with the following UR (no CORS enabled) :

https://www.jpl.nasa.gov/spaceimages/images/wallpaper/PIA20878-640x350.jpg

set to use proxy. The test is a success if the image renders on the map.
set to not use proxy. The test is a success if the image fails to render on the map. It is expected to themap to fail to render because the server the image comes from has no CORS enabled.

**Comment by alberto-acevedo** [comment]
Unrelated to this issue of point and proxy, I also added support for WMS and proxy in branch 97. You need geoserver in a separate tomcat to simulate the use of extenal WMS services requiringa proxy.

**Comment by alberto-acevedo** [comment]
test case :

Use branch feature/emp3-web#97-ww-proxy

.Use following URL that comes from a server that is not CORS enable:
https://www.jpl.nasa.gov/spaceimages/images/wallpaper/PIA20878-640x350.jpg

**Comment by alberto-acevedo** [comment]
Try again the test case. Use branch feature/emp3-web#97-ww-proxy.

https://www.jpl.nasa.gov/spaceimages/images/wallpaper/PIA20878-640x350.jpg
